server:
  port: 8080
  servlet:
    context-path: /gsdn

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gsdn_community?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: password
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: password
  profiles:
    active: dev

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

sa-token:
  token-name: token
  token-style: random-128
  is-read-cookie: true
  is-read-header: true
  is-read-body: false
  is-concurrent: true
  is-share: true
  is-log: true
  timeout: -1
  active-timeout: -1

oss:
  endpoint: your endpoint
  url: your url
  bucket-name: your bucket-name
  access-key-id: your access-key-id
  access-key-secret: your access-key-secret
  file-dir: your file-dir