version: '3.8'

networks:
  1panel-network:
    external: true

services:
  gsdn-community:
    image: gsdn_community
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gsdn_community
    ports:
      - "8080:8080"
    volumes:
      - ./gsdn-community.jar:/gsdn-community.jar
      - /tmp
    command: java -jar /gsdn-community.jar
    networks:
      - 1panel-network